with(x , plot(Date + Time ,Sub_metering_1 , xlab="",ylab="Energy Sub Meter", type="n"))
with(x , lines(Date + Time , Sub_metering_1 , col="black"))
with(x , lines(Date + Time , Sub_metering_2 , col="red"))
with(x , lines(Date + Time , Sub_metering_3 , col="blue"))
legend('topright' , col=c('black' , 'red','blue') , lty = 1 , legend = c('Sub_metering_1' ,'Sub_metering_2' ,'Sub_metering_3'))
dev.copy(png , file="plot3.png" , height=480 , width=480)
dev.off()